name: Build and deploy asset-bucket-proxy
on:
  push:
    branches:
    - main
env:
  docker_image: ghcr.io/${{ github.repository }}:${{ github.sha }}
jobs:
  build:
    name: Build and push Docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.docker_image }}
  deployToDev:
    name: Deploy to dev-gcp
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to dev-gcp
      uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-gcp
        RESOURCE: nais/nais.yml
        VARS: nais/dev-gcp.json
        VAR: image=${{ env.docker_image }}